export const models = [
  '5crystal.obj',
  'chalk1.obj',
  'crystal.obj',
  'crystal1.obj',
  'crystal2.obj',
  'crystal3.obj',
  'cube1.obj',
  'cubic2.obj',
  'egg1.obj',
  'gem.obj',
  'icosphere.obj',
  'icosphere-beveledge.obj',
  'icosphere-bevelverts.obj',
  'nugget.obj',
  'shard.obj',
  'spiky2.obj',
];

export const combomodels = [
  '5crystal.obj',
  '5crystal2.obj',
  'chalk1.obj',
  'crystal2.obj',
  'crystal3.obj',
  'cube1.obj',
  'cubic2.obj',
  'icosphere.obj',
  'shard.obj',
];